import { useState, useEffect } from 'react';
import { 
  CORE_SERVICES, 
  FEATURED_PRODUCTS, 
  CASE_STUDIES_TIMELINE, 
  TESTIMONIALS, 
  BLOG_POSTS
} from '../constants';
import { ServiceItem, ProductItem, TestimonialItem, BlogPost, CTAContent, FooterContent } from '../types';

interface HomePageContent {
  badge: string;
  heroTitle: string;
  heroDesc: string;
  ctaPrimary: string;
  ctaSecondary: string;
}

interface SiteContent {
  home: HomePageContent;
  services: ServiceItem[];
  products: ProductItem[];
  timeline: any[];
  testimonials: TestimonialItem[];
  blogs: BlogPost[];
  cta: CTAContent;
  footer: FooterContent;
}

const DEFAULT_HOME: HomePageContent = {
  badge: "Transforming Businesses Through AI & IoT",
  heroTitle: "Your Vision, Engineered with Intelligence.",
  heroDesc: "DeepNeurax Technologies combines the power of AI, IoT, cloud, and modern software engineering to build products that accelerate growth and optimize operations.",
  ctaPrimary: "Start Your Project",
  ctaSecondary: "Explore Services"
};

const DEFAULT_CTA: CTAContent = {
  title: "Ready to Build Something Next-Level?",
  subtitle: "Let's transform your business with intelligent digital solutions",
  buttonText: "Start Your Project"
};

const DEFAULT_FOOTER: FooterContent = {
  companyDescription: "Empowering organizations through secure, scalable, and intelligent digital technologies that accelerate growth and enable long-term sustainability.",
  copyrightText: "© 2025 DeepNeurax Technologies. All Rights Reserved.",
  badgeText: "" // Removed text
};

export function useContent() {
  const [content, setContent] = useState<SiteContent>({
    home: DEFAULT_HOME,
    services: CORE_SERVICES,
    products: FEATURED_PRODUCTS,
    timeline: CASE_STUDIES_TIMELINE,
    testimonials: TESTIMONIALS,
    blogs: BLOG_POSTS,
    cta: DEFAULT_CTA,
    footer: DEFAULT_FOOTER
  });

  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function fetchContent() {
      try {
        // We try to fetch the JSON files generated by Netlify CMS.
        // If they don't exist (404), we catch the error and keep the default constants.
        
        const [
          homeRes, 
          servicesRes, 
          productsRes, 
          timelineRes, 
          testimonialsRes, 
          blogsRes,
          ctaRes,
          footerRes
        ] = await Promise.allSettled([
          fetch('/content/home.json'),
          fetch('/content/services.json'),
          fetch('/content/products.json'),
          fetch('/content/timeline.json'),
          fetch('/content/testimonials.json'),
          fetch('/content/blogs.json'),
          fetch('/content/cta.json'),
          fetch('/content/footer.json')
        ]);

        const newContent = { ...content };

        if (homeRes.status === 'fulfilled' && homeRes.value.ok) {
          newContent.home = await homeRes.value.json();
        }
        if (servicesRes.status === 'fulfilled' && servicesRes.value.ok) {
          const data = await servicesRes.value.json();
          if(data.items) newContent.services = data.items;
        }
        if (productsRes.status === 'fulfilled' && productsRes.value.ok) {
          const data = await productsRes.value.json();
          if(data.items) newContent.products = data.items;
        }
        if (timelineRes.status === 'fulfilled' && timelineRes.value.ok) {
           const data = await timelineRes.value.json();
           if(data.items) {
             newContent.timeline = data.items.map((item: any) => ({
                ...item,
                relatedIds: item.relatedIds || []
             }));
           }
        }
        if (testimonialsRes.status === 'fulfilled' && testimonialsRes.value.ok) {
           const data = await testimonialsRes.value.json();
           if(data.items) newContent.testimonials = data.items;
        }
        if (blogsRes.status === 'fulfilled' && blogsRes.value.ok) {
           const data = await blogsRes.value.json();
           if(data.items) newContent.blogs = data.items;
        }
        if (ctaRes.status === 'fulfilled' && ctaRes.value.ok) {
           const data = await ctaRes.value.json();
           // The CMS saves fields directly in the object for singleton files (like home.json)
           if(data) newContent.cta = data;
        }
        if (footerRes.status === 'fulfilled' && footerRes.value.ok) {
           const data = await footerRes.value.json();
           if(data) newContent.footer = data;
        }

        setContent(newContent);
      } catch (error) {
        console.error("Failed to load CMS content, using defaults", error);
      } finally {
        setIsLoading(false);
      }
    }

    fetchContent();
  }, []);

  return { content, isLoading };
}